name: Build and deploy PHP app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: TubesWebAppKel9
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PHP_VERSION: '8.2'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, bcmath, xml, curl, json

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Install frontend dependencies
        run: npm ci --no-audit --no-fund

      - name: Build frontend assets
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: php-app
          path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: php-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.TUBES9_CC }}
          package: .
          clean: true
          restart: true
